// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csniibgggnuapwauguvx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbmlpYmdnZ251YXB3YXVndXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzY0NDQsImV4cCI6MjA2NTU1MjQ0NH0.ETF3-srvBU3Z-GHUx-gBTSxJaY-gVpAYTWu8NwlLhnY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);